### ISSUE TITLE
how is the speed of this tracker? It seems MOT challenge site gives 0.6 Hz which is rather low

### ISSUE THREAD

**Issue by rambleramble** [phil-bergmann/tracking_wo_bnw#11]
Thanks for this great work,

According to the MOT challenge website:

https://motchallenge.net/results/CVPR_2019_Tracking_Challenge/

The speed is only 0.6 Hz, is it a true reflection of this repo?

Do you have a more recent analysis on the speed performance?

Thanks in advance!

**Comment by timmeinhardt** [comment]
I just tested Tracktor++ on the CVPR 2019 test set and it took 1667 seconds to finish all 4 sequences. I updated the MOTChallenge webpage accordingly.

**Comment by rambleramble** [comment]
thanks for the update

**Comment by timmeinhardt** [comment]
We did not evaluate the runtime of the different steps in our Tracktor algorithm. However, there are multiple things one could do to speed it up. Our object detector is called multiple times. I think the number of calls per frame could be reduced. Running an object detector with a different backbone, e.g., ResNet34 instead of ResNet101, is a possibility if top tracking performance is not essential.

Changing the trajectory killing or bounding box initialisation thresholds should change the number of detected objects but I think the potential for reducing the runtime is comparatively small.

But again, this is something that has to be evaluated to be really sure.

**Comment by timmeinhardt** [comment]
Can we close this issue?
