### ISSUE TITLE
can't find the module named "tracktor.config"

### ISSUE THREAD

**Issue by JOVYOO** [phil-bergmann/tracking_wo_bnw#164]
I created a Python 3.7 environment through anaconda.
I followed the author's steps exactly and as a result I ran into a problem in the screenshot. 
It prompts me that I don't have a "tracktor.config" module. 
But I couldn't find this module. How do I install it.
![capture_1](https://user-images.githubusercontent.com/71836980/159901588-8043f9bc-b23a-4c1e-8c7f-d3e03de090fe.jpg)

**Comment by timmeinhardt** [comment]
The provided README.md works for `virtualenv` not `anaconda` I am not sure how to adapt this. Maybe look into [this](https://stackoverflow.com/questions/41060382/using-pip-to-install-packages-to-anaconda-environment).

**Comment by WuJune** [comment]
Actually, it has nothing to do with `conda` or `venv`

That is because you use `-e git+ssh://git@github.com/phil-bergmann/tracking_wo_BnW@b47f66d20cfa1042c8d8a753f03eb26904489421#egg=tracktor
` whichs show in `requirements.txt`, overwrites `src/tracktor`

In fact, you need to merge them and then run `pip install - e .q

**Comment by timmeinhardt** [comment]
I removed the line from the `requirements.txt`.
