### ISSUE TITLE
Questions about the bounding box regression part

### ISSUE THREAD

**Issue by tjz0714** [phil-bergmann/tracking_wo_bnw#31]
Thanks for your excellent work! After reading your code I have some questions about the bounding box regression part:
1) If we use public detections on MOT datasets, does bbox regresson still work? I mean, the bounding box regression needs to train the weights so as to refine the coordinates when testing. FPN and Faster
RCNN has already trained this in the loss. If we use public detections, how can we get the weights to do bbox regression?
2) In your code, I didn't find the weights of bounding box regression. It seems like you directly get the features through network and feed them to the formulations. 

Thank you very much!

**Comment by timmeinhardt** [comment]
1. The weights of the Faster-RCNN + FPN object detector are trained during the regular object detection training. We just use the bounding box regressor as it is after the detection training and apply it to the publich detections from frame to frame. There is not training during test time.
2. There are no explicit weights for the regression. But we provide the weights of the object detector which includes the regressor weights. In order to regress we always need to run the entire object detector for the image features and the RoI pooling.

**Comment by timmeinhardt** [comment]
Can we close this issue?
