### ISSUE TITLE
public detections and private detections? 

### ISSUE THREAD

**Issue by XiongDei** [phil-bergmann/tracking_wo_bnw#44]
I am confusing about public detections and private detections concept. My understanding after reading codes is the public detections are generated by 'fpn' while private detections are from 'faster rcnn'. Is this correct? Thanks.

**Comment by timmeinhardt** [comment]
No this is not correct. The FPN has nothing to do with public or private detections but is just part of the object detector architecture. Public detections are provided by the challenge and are either from a DPM, FRCNN or SDP object detector and ensure the comparability between different tracking methods such that the performance gain is due to improvement in the tracking and not detection part. For MOT17 with private detections one can apply any object detector.

**Comment by biubug6** [comment]
Hi, 
shell
'''
boxes, scores = self.obj_detect.predict_boxes(blob['img'], dets)
'''
in tracker.py 264lines. 
It means you change MOT dets(regress again) as final det boxs. It is conflicted with public detections?

**Comment by timmeinhardt** [comment]
Yes, we are regressing (changing) the MOT public detections and thereby we are achieving multi-object tracking from frame to frame. What do you mean by "conflicted with public detections"?

**Comment by timmeinhardt** [comment]
Can we close this issue?

**Comment by XiongDei** [comment]
yes. thanks

Tim Meinhardt <notifications@github.com> 于 2020年2月19日周三 下午11:25写道：

**Comment by dulucas** [comment]
> Yes, we are regressing (changing) the MOT public detections and thereby we are achieving multi-object tracking from frame to frame. What do you mean by "conflicted with public detections"?

Hi, I have the same question with @biubug6 , I didn't find the code to use the detected boxes from frame T-1 to obtain the boxes of frame T, Could you please help me with it? thx
