### ISSUE TITLE
Result with default configuration

### ISSUE THREAD

**Issue by Spritea** [phil-bergmann/tracking_wo_bnw#92]
Thanks for your code!

I'm trying this code with default configuration. All packages are the same with `requirement.txt`.
1. In my understanding, the default model is faster rcnn+fpn, with motion model and reid model, but I don't quite understand that the motion model seems to be closed in `tracktor.yaml`. The code is shown below.
>motion_model:
      enabled: False
2. When I run this command `python experiments/scripts/test_tracktor.py` with default configuration, it runs well. But the result shows it only takes effect for partial frames, I'm not sure whether it's the expected result. 
>INFO - main - Initializing object detector.
INFO - main - Tracking: MOT17-02-FRCNN
100%|█████████████████████████████████████████| 600/600 [03:43<00:00,  2.68it/s]
INFO - main - Tracks found: 92
INFO - main - Runtime for MOT17-02-FRCNN: 223.57 s.
INFO - main - Writing predictions to: /home/ali/cws/from-github/tracking_wo_bnw/output/tracktor/MOT17/Tracktor++
INFO - main - Tracking: MOT17-04-FRCNN
100%|███████████████████████████████████████| 1050/1050 [07:38<00:00,  2.29it/s]
INFO - main - Tracks found: 81
INFO - main - Runtime for MOT17-04-FRCNN: 458.93 s.
INFO - main - Writing predictions to: /home/ali/cws/from-github/tracking_wo_bnw/output/tracktor/MOT17/Tracktor++
INFO - main - Tracking: MOT17-05-FRCNN
100%|█████████████████████████████████████████| 837/837 [02:26<00:00,  5.71it/s]
INFO - main - Tracks found: 110
INFO - main - Runtime for MOT17-05-FRCNN: 146.53 s.
INFO - main - Writing predictions to: /home/ali/cws/from-github/tracking_wo_bnw/output/tracktor/MOT17/Tracktor++
3. There are 4 kinds of results in the unzipped `tracking_wo_bnw-output_v2`. In my understanding, the `MOT17-**.txt` file in `faster_rcnn_fpn_training_not_17` is the detection result when training faster rcnn+fpn model on MOT17. The others are in the `tracktor/MOT17/Tracktor++` folder. Are they results of MOT17 challenge with 3 **public** detectors, and what we get by running default test command above is the result with **private** detector(faster rcnn+fpn trained in MOT17)? Can we reproduce the public detector results with this project?
Could you please clarify the points? Please excuse a fresh :). Thanks a lot!

**Comment by timmeinhardt** [comment]
1. In the paper we present two kind of motion models: (i) the camera motion compensation and (ii) the constand velocity assumption motion model. The current default configuration has only the first one activated by setting `do_align=True`.
2. I am not sure what you mean by partial frames and how this relates to the command line output shown.
3. The default configuration is with *public* detections, more precisely, for Faster R-CNN public detections. In order to produce private results or the public detections results for DPM or SDP detections. one has to change the default config.

**Comment by Spritea** [comment]
Thanks for your reply!

1.  Solved.

2. I mean the output result of running default configuration. I found the output files in `tracktor/MOT17/Tracktor++` folder are `MOT17-02-FRCNN.txt`, `MOT17-04-FRCNN.txt`, `MOT17-05-FRCNN.txt`, `MOT17-09-FRCNN.txt`, `MOT17-10-FRCNN.txt`, `MOT17-11-FRCNN.txt`, `MOT17-13-FRCNN.txt`. But the result file unzipped from `tracking_wo_bnw-output_v2` starts from `MOT17-01-FRCNN.txt` to `MOT17-14-FRCNN.txt` one by one. So I don't quite understand this difference.

3. I guess faster rcnn, as a public detector, should be naive without modification including fpn. But the default configuration uses faster rcnn with fpn. Is that applicable?

**Comment by timmeinhardt** [comment]
2. Thats because we included all sequences including the test sequences and you are running only the train sequences. Please check the config and the dataset entry with its references to the `factory.py` file for more details on all the splits.
3. What do you mean by applicable? In public detection mode we are not detecing any bounding boxes but the Faster R-CNN + FPN is only used for classification and regression of the public detections.

**Comment by Spritea** [comment]
I thought the Faster RCNN+FPN is used in detection, but now I understand.

Thanks for your detailed explanation!
